easy_admin:
    
    site_name: '<img src="/images/photo/goaladmin.png" style="width:120px">'
    
    design:
      menu:
        - { entity: 'Utilisateur', icon: 'user' }
        - { entity: 'Agence', icon: 'building' }
        - { entity: 'Client', icon: 'user' }
        - { entity: 'Terrain', icon: 'user' }
    
    entities:
        Utilisateur:
            class: App\Entity\Utilisateur
           
        Agence:
            class: App\Entity\Agence
     
        Client:
            class: App\Entity\Client

        
        Terrain:
            class: App\Entity\Terrain
        
